### ISSUE TITLE
Open a Pull Request is still tiny

### ISSUE THREAD

**Issue by ike709** [MCHSL/sane-github#16]
![image](https://user-images.githubusercontent.com/5714543/87701142-12d42380-c75d-11ea-8f8a-92e48898c3fb.png)

**Comment by ZeWaka** [comment]
one of these fixes it, i forget which:
```css
#files {
	margin-left: 0 !important;
	width: 100% !important;
}

:not(#discussion_bucket):not(#wiki-content):not(.container-xl) > .gutter-condensed:not(.js-pinned-items-reorder-list).gutter-lg:not(.flex-column) > .flex-shrink-0:first-child {
	width: 100% !important;
}

.repository-content > .d-flex.width-full > .flex-column {
    width: 78% !important;
}
```
