### ISSUE TITLE
PR checks flow off the page

### ISSUE THREAD

**Issue by ZeWaka** [MCHSL/sane-github#3]
![image](https://user-images.githubusercontent.com/4741640/85482722-5a112f00-b578-11ea-96bb-64bd02e1c8ea.png)
https://github.com/goonstation/goonstation/pull/1197/checks

**Comment by ZeWaka** [comment]
solvable by this fuckery:
```css
.repository-content.d-flex > .width-full {
	width: 60% !important;
}

.repository-content.d-flex > .d-flex.width-full > .flex-column {
	width: 100% !important;
}
```
