### ISSUE TITLE
projects filter is off the page

### ISSUE THREAD

**Issue by ZeWaka** [MCHSL/sane-github#4]
![image](https://user-images.githubusercontent.com/4741640/85482785-7ad98480-b578-11ea-9042-ea1f08d8c1e8.png)
https://github.com/goonstation/goonstation/projects/1

**Comment by ZeWaka** [comment]
solvable by 
```css
.full-width .repository-content {
    width: 77% !important;
}
```
